name: Build Project

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '14'  # Specify the version of Node.js to use

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build the project
        run: npm run build  # Run the build command from package.json
